#!/bin/bash
# Install Duo Authentication Proxy on the host machine.
# This proxy receives RADIUS requests from the NetMon backend container
# and forwards them to Duo's cloud for Push verification.
#
# Usage:
#   sudo bash install_duo_authproxy.sh --ikey DIXXXXXXXXXXXXXXXXXX \
#       --skey YourSecretKey --apihost api-XXXXXXXX.duosecurity.com
#
# The script will:
#   1. Install build dependencies
#   2. Download and compile the Duo Auth Proxy
#   3. Generate a RADIUS shared secret
#   4. Write /opt/duoauthproxy/conf/authproxy.cfg
#   5. Enable and start the systemd service
#   6. Print the RADIUS secret to paste into NetMon .env or Settings UI

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[INFO]${NC}  $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error(){ echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
step() { echo -e "\n${BLUE}━━━ $1 ━━━${NC}"; }

# ─── Parse arguments ──────────────────────────────────────────────────────────
IKEY="" SKEY="" APIHOST="" RADIUS_PORT=1812
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ikey)    IKEY="$2";    shift 2 ;;
    --skey)    SKEY="$2";    shift 2 ;;
    --apihost) APIHOST="$2"; shift 2 ;;
    --port)    RADIUS_PORT="$2"; shift 2 ;;
    *) error "Unknown option: $1" ;;
  esac
done

# Prompt for missing values
if [ -z "$IKEY" ];    then read -rp "Duo Integration Key (ikey): " IKEY;    fi
if [ -z "$SKEY" ];    then read -rp "Duo Secret Key (skey): "      SKEY;    fi
if [ -z "$APIHOST" ]; then read -rp "Duo API Hostname: "           APIHOST; fi

[ -z "$IKEY" ]    && error "Integration key is required"
[ -z "$SKEY" ]    && error "Secret key is required"
[ -z "$APIHOST" ] && error "API hostname is required"

# Must be root
[ "$(id -u)" -ne 0 ] && error "Please run as root or with sudo"

# ─── Detect OS ────────────────────────────────────────────────────────────────
step "Detecting OS"
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_ID="${ID}"
else
  OS_ID="unknown"
fi
log "OS: ${OS_ID}"

# ─── Install build dependencies ──────────────────────────────────────────────
step "Installing build dependencies"
case "${OS_ID}" in
  ubuntu|debian|pop|linuxmint)
    apt-get update -qq
    apt-get install -y -qq python3 python3-dev python3-pip python3-venv \
      build-essential libffi-dev libssl-dev curl openssl
    ;;
  centos|rhel|rocky|almalinux|ol|fedora)
    yum install -y -q python3 python3-devel python3-pip \
      gcc make libffi-devel openssl-devel curl openssl \
      2>/dev/null || dnf install -y -q python3 python3-devel python3-pip \
      gcc make libffi-devel openssl-devel curl openssl
    ;;
  *)
    warn "OS '${OS_ID}' not explicitly supported — assuming deps are present"
    ;;
esac

# ─── Download Duo Auth Proxy ─────────────────────────────────────────────────
step "Downloading Duo Authentication Proxy"
TMPDIR=$(mktemp -d)
cd "$TMPDIR"
DL_URL="https://dl.duosecurity.com/duoauthproxy-latest-src.tgz"
log "Downloading from $DL_URL ..."
curl -fsSL "$DL_URL" -o duoauthproxy-latest-src.tgz
tar xzf duoauthproxy-latest-src.tgz
cd duoauthproxy-*-src

# ─── Build + Install ─────────────────────────────────────────────────────────
step "Building Duo Auth Proxy (this may take a few minutes)"
make
cd duoauthproxy-build
./install --install-dir /opt/duoauthproxy --service-user nobody --log-group nobody --create-init-script yes 2>/dev/null || \
  ./install --install-dir /opt/duoauthproxy --service-user nobody --create-init-script yes 2>/dev/null || \
  ./install --install-dir /opt/duoauthproxy

# ─── Generate RADIUS shared secret ───────────────────────────────────────────
step "Generating RADIUS shared secret"
RADIUS_SECRET=$(openssl rand -hex 16)
log "RADIUS secret: ${RADIUS_SECRET}"

# ─── Write config ─────────────────────────────────────────────────────────────
step "Writing authproxy.cfg"
cat > /opt/duoauthproxy/conf/authproxy.cfg <<EOF
; Duo Authentication Proxy configuration
; Generated by install_duo_authproxy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

[duo_only_client]

[radius_server_duo_only]
ikey=${IKEY}
skey=${SKEY}
api_host=${APIHOST}
failmode=safe
client=duo_only_client
radius_ip_1=0.0.0.0
radius_secret_1=${RADIUS_SECRET}
port=${RADIUS_PORT}
EOF
chmod 600 /opt/duoauthproxy/conf/authproxy.cfg
log "Config written to /opt/duoauthproxy/conf/authproxy.cfg"

# ─── Enable + start service ──────────────────────────────────────────────────
step "Starting Duo Auth Proxy service"
if command -v systemctl >/dev/null 2>&1; then
  # The installer usually creates a systemd unit or init script
  if [ -f /etc/systemd/system/duoauthproxy.service ]; then
    systemctl daemon-reload
    systemctl enable duoauthproxy
    systemctl restart duoauthproxy
  elif [ -f /etc/init.d/duoauthproxy ]; then
    /etc/init.d/duoauthproxy restart
    systemctl enable duoauthproxy 2>/dev/null || true
  else
    # Create a basic systemd unit
    cat > /etc/systemd/system/duoauthproxy.service <<UNIT
[Unit]
Description=Duo Authentication Proxy
After=network.target

[Service]
Type=forking
ExecStart=/opt/duoauthproxy/bin/authproxyctl start
ExecStop=/opt/duoauthproxy/bin/authproxyctl stop
Restart=on-failure

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload
    systemctl enable --now duoauthproxy
  fi
elif [ -f /etc/init.d/duoauthproxy ]; then
  /etc/init.d/duoauthproxy restart
fi
log "Duo Auth Proxy service started"

# ─── Cleanup ──────────────────────────────────────────────────────────────────
rm -rf "$TMPDIR"

# ─── Summary ──────────────────────────────────────────────────────────────────
step "Installation Complete!"
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Duo Authentication Proxy Installed                         ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC} Install dir:  /opt/duoauthproxy                              ${GREEN}║${NC}"
echo -e "${GREEN}║${NC} Config:       /opt/duoauthproxy/conf/authproxy.cfg            ${GREEN}║${NC}"
echo -e "${GREEN}║${NC} RADIUS port:  ${RADIUS_PORT}                                          ${GREEN}║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC} ${YELLOW}RADIUS Shared Secret:${NC}                                       ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}   ${YELLOW}${RADIUS_SECRET}${NC}"
echo -e "${GREEN}║${NC}                                                              ${GREEN}║${NC}"
echo -e "${GREEN}║${NC} Add this to your NetMon .env file:                            ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}   DUO_ENABLED=true                                            ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}   DUO_RADIUS_SECRET=${RADIUS_SECRET}            ${GREEN}║${NC}"
echo -e "${GREEN}║${NC}                                                              ${GREEN}║${NC}"
echo -e "${GREEN}║${NC} Or configure via Settings → MFA in the web UI.               ${GREEN}║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
